# utils/logic.py

def generate_summary(data):
    """
    Takes a dictionary of patient data and returns a formatted string.
    """
    summary = f"""
    ### 📋 Patient Pre-Visit Summary
    ---
    **Patient Name:** {data.get('name', 'N/A')}
    **Primary Concern:** {data.get('reason', 'N/A')}
    **Severity Level:** {data.get('severity', 'N/A')}/10
    **Duration:** {data.get('duration', 'N/A')}
    **Additional Notes:** {data.get('notes', 'None provided')}
    ---
    *Disclaimer: This report was generated by an AI assistant and should be verified by a medical professional.*
    """
    return summary

def get_next_question(current_step):
    """
    Determines the next question based on how many messages have been exchanged.
    """
    questions = {
        0: "Hello! I'm HealthAssist. To start, what is your **full name**?",
        1: "Nice to meet you. In a few words, what is the **primary reason** for your visit?",
        2: "On a scale of **1 to 10**, how severe is this discomfort?",
        3: "How many **days** has this been bothering you?",
        4: "Are there any **other symptoms** or allergies you'd like the doctor to know about?"
    }
    return questions.get(current_step, "Thank you! I have all the info. Would you like me to generate your report?")